workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/haroldorquesta/test-orq-python-client/refs/heads/main/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/haroldorquesta/test-orq-python-client/refs/heads/main/openapi-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-oas
targets:
    orq:
        target: python
        source: orq-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-oas-code-samples
            blocking: false
