"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class APIEndpoint(str, Enum):
    ROOT_V1_CHAT_COMPLETIONS = "/v1/chat/completions"
    ROOT_V1_EMBEDDINGS = "/v1/embeddings"
    ROOT_V1_FIM_COMPLETIONS = "/v1/fim/completions"
    ROOT_V1_MODERATIONS = "/v1/moderations"
