"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ArchiveFTModelOutObject(str, Enum):
    MODEL = "model"


class ArchiveFTModelOutTypedDict(TypedDict):
    id: str
    object: ArchiveFTModelOutObject
    archived: NotRequired[bool]


class ArchiveFTModelOut(BaseModel):
    id: str

    OBJECT: Annotated[
        Annotated[
            Optional[ArchiveFTModelOutObject],
            AfterValidator(validate_const(ArchiveFTModelOutObject.MODEL)),
        ],
        pydantic.Field(alias="object"),
    ] = ArchiveFTModelOutObject.MODEL

    archived: Optional[bool] = True
