"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchjobout import BatchJobOut, BatchJobOutTypedDict
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BatchJobsOutObject(str, Enum):
    LIST = "list"


class BatchJobsOutTypedDict(TypedDict):
    total: int
    data: NotRequired[List[BatchJobOutTypedDict]]
    object: BatchJobsOutObject


class BatchJobsOut(BaseModel):
    total: int

    data: Optional[List[BatchJobOut]] = None

    OBJECT: Annotated[
        Annotated[
            Optional[BatchJobsOutObject],
            AfterValidator(validate_const(BatchJobsOutObject.LIST)),
        ],
        pydantic.Field(alias="object"),
    ] = BatchJobsOutObject.LIST
