"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionresponse import (
    ChatCompletionResponse,
    ChatCompletionResponseTypedDict,
)
from .completionevent import CompletionEvent, CompletionEventTypedDict
from typing import AsyncGenerator, Generator, Union


ChatCompletionV1ChatCompletionsPostResponseTypedDict = Union[
    ChatCompletionResponseTypedDict,
    Union[
        Generator[CompletionEventTypedDict, None, None],
        AsyncGenerator[CompletionEventTypedDict, None],
    ],
]


ChatCompletionV1ChatCompletionsPostResponse = Union[
    ChatCompletionResponse,
    Union[
        Generator[CompletionEvent, None, None], AsyncGenerator[CompletionEvent, None]
    ],
]
