"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deltamessage import DeltaMessage, DeltaMessageTypedDict
from enum import Enum
from test_sdk.types import BaseModel
from typing_extensions import TypedDict


class FinishReason(str, Enum):
    STOP = "stop"
    LENGTH = "length"
    MODEL_LENGTH = "model_length"
    ERROR = "error"
    TOOL_CALLS = "tool_calls"


class ChatCompletionChoiceTypedDict(TypedDict):
    index: int
    message: DeltaMessageTypedDict
    finish_reason: FinishReason


class ChatCompletionChoice(BaseModel):
    index: int

    message: DeltaMessage

    finish_reason: FinishReason
