"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FilePurpose(str, Enum):
    FINE_TUNE = "fine-tune"
    BATCH = "batch"
