"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .completionevent import CompletionEvent, CompletionEventTypedDict
from .fimcompletionresponse import FIMCompletionResponse, FIMCompletionResponseTypedDict
from typing import AsyncGenerator, Generator, Union


FimCompletionV1FimCompletionsPostResponseTypedDict = Union[
    FIMCompletionResponseTypedDict,
    Union[
        Generator[CompletionEventTypedDict, None, None],
        AsyncGenerator[CompletionEventTypedDict, None],
    ],
]


FimCompletionV1FimCompletionsPostResponse = Union[
    FIMCompletionResponse,
    Union[
        Generator[CompletionEvent, None, None], AsyncGenerator[CompletionEvent, None]
    ],
]
