"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FineTuneableModel(str, Enum):
    r"""The name of the model to fine-tune."""

    OPEN_MISTRAL_7B = "open-mistral-7b"
    MISTRAL_SMALL_LATEST = "mistral-small-latest"
    CODESTRAL_LATEST = "codestral-latest"
    MISTRAL_LARGE_LATEST = "mistral-large-latest"
    OPEN_MISTRAL_NEMO = "open-mistral-nemo"
