"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageurl import ImageURL, ImageURLTypedDict
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional, Union
from typing_extensions import Annotated, TypedDict


class ImageURLChunkType(str, Enum):
    IMAGE_URL = "image_url"


ImageURLChunkImageURLTypedDict = Union[ImageURLTypedDict, str]


ImageURLChunkImageURL = Union[ImageURL, str]


class ImageURLChunkTypedDict(TypedDict):
    r"""{\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image/png;base64,iVBORw0"""

    image_url: ImageURLChunkImageURLTypedDict
    type: ImageURLChunkType


class ImageURLChunk(BaseModel):
    r"""{\"type\":\"image_url\",\"image_url\":{\"url\":\"data:image/png;base64,iVBORw0"""

    image_url: ImageURLChunkImageURL

    TYPE: Annotated[
        Annotated[
            Optional[ImageURLChunkType],
            AfterValidator(validate_const(ImageURLChunkType.IMAGE_URL)),
        ],
        pydantic.Field(alias="type"),
    ] = ImageURLChunkType.IMAGE_URL
