"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jobout import JobOut, JobOutTypedDict
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class JobsOutObject(str, Enum):
    LIST = "list"


class JobsOutTypedDict(TypedDict):
    total: int
    data: NotRequired[List[JobOutTypedDict]]
    object: JobsOutObject


class JobsOut(BaseModel):
    total: int

    data: Optional[List[JobOut]] = None

    OBJECT: Annotated[
        Annotated[
            Optional[JobsOutObject], AfterValidator(validate_const(JobsOutObject.LIST))
        ],
        pydantic.Field(alias="object"),
    ] = JobsOutObject.LIST
