"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SampleType(str, Enum):
    PRETRAIN = "pretrain"
    INSTRUCT = "instruct"
    BATCH_REQUEST = "batch_request"
    BATCH_RESULT = "batch_result"
    BATCH_ERROR = "batch_error"
