"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class Source(str, Enum):
    UPLOAD = "upload"
    REPOSITORY = "repository"
    MISTRAL = "mistral"
