"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .textchunk import TextChunk, TextChunkTypedDict
from enum import Enum
from test_sdk.types import BaseModel
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypedDict


SystemMessageContentTypedDict = Union[str, List[TextChunkTypedDict]]


SystemMessageContent = Union[str, List[TextChunk]]


class Role(str, Enum):
    SYSTEM = "system"


class SystemMessageTypedDict(TypedDict):
    content: SystemMessageContentTypedDict
    role: NotRequired[Role]


class SystemMessage(BaseModel):
    content: SystemMessageContent

    role: Optional[Role] = Role.SYSTEM
