"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, TypedDict


class TextChunkType(str, Enum):
    TEXT = "text"


class TextChunkTypedDict(TypedDict):
    text: str
    type: TextChunkType


class TextChunk(BaseModel):
    text: str

    TYPE: Annotated[
        Annotated[
            Optional[TextChunkType], AfterValidator(validate_const(TextChunkType.TEXT))
        ],
        pydantic.Field(alias="type"),
    ] = TextChunkType.TEXT
