"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .function import Function, FunctionTypedDict
from .tooltypes import ToolTypes
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, TypedDict


class ToolTypedDict(TypedDict):
    function: FunctionTypedDict
    type: ToolTypes


class Tool(BaseModel):
    function: Function

    TYPE: Annotated[
        Annotated[
            Optional[ToolTypes], AfterValidator(validate_const(ToolTypes.FUNCTION))
        ],
        pydantic.Field(alias="type"),
    ] = ToolTypes.FUNCTION
