"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .functioncall import FunctionCall, FunctionCallTypedDict
from .tooltypes import ToolTypes
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolCallTypedDict(TypedDict):
    function: FunctionCallTypedDict
    id: NotRequired[str]
    type: ToolTypes


class ToolCall(BaseModel):
    function: FunctionCall

    id: Optional[str] = "null"

    TYPE: Annotated[
        Annotated[
            Optional[ToolTypes], AfterValidator(validate_const(ToolTypes.FUNCTION))
        ],
        pydantic.Field(alias="type"),
    ] = ToolTypes.FUNCTION
