"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .functionname import FunctionName, FunctionNameTypedDict
from .tooltypes import ToolTypes
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, TypedDict


class ToolChoiceTypedDict(TypedDict):
    r"""ToolChoice is either a ToolChoiceEnum or a ToolChoice"""

    function: FunctionNameTypedDict
    r"""this restriction of `Function` is used to select a specific function to call"""
    type: ToolTypes


class ToolChoice(BaseModel):
    r"""ToolChoice is either a ToolChoiceEnum or a ToolChoice"""

    function: FunctionName
    r"""this restriction of `Function` is used to select a specific function to call"""

    TYPE: Annotated[
        Annotated[
            Optional[ToolTypes], AfterValidator(validate_const(ToolTypes.FUNCTION))
        ],
        pydantic.Field(alias="type"),
    ] = ToolTypes.FUNCTION
