"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from test_sdk.types import BaseModel
from test_sdk.utils import validate_const
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UnarchiveFTModelOutObject(str, Enum):
    MODEL = "model"


class UnarchiveFTModelOutTypedDict(TypedDict):
    id: str
    object: UnarchiveFTModelOutObject
    archived: NotRequired[bool]


class UnarchiveFTModelOut(BaseModel):
    id: str

    OBJECT: Annotated[
        Annotated[
            Optional[UnarchiveFTModelOutObject],
            AfterValidator(validate_const(UnarchiveFTModelOutObject.MODEL)),
        ],
        pydantic.Field(alias="object"),
    ] = UnarchiveFTModelOutObject.MODEL

    archived: Optional[bool] = False
