"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contentchunk import ContentChunk, ContentChunkTypedDict
from enum import Enum
from test_sdk.types import BaseModel
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypedDict


UserMessageContentTypedDict = Union[str, List[ContentChunkTypedDict]]


UserMessageContent = Union[str, List[ContentChunk]]


class UserMessageRole(str, Enum):
    USER = "user"


class UserMessageTypedDict(TypedDict):
    content: UserMessageContentTypedDict
    role: NotRequired[UserMessageRole]


class UserMessage(BaseModel):
    content: UserMessageContent

    role: Optional[UserMessageRole] = UserMessageRole.USER
